# Generated by Django 2.2.5 on 2019-10-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grinch', '0002_auto_20191010_0512'),
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='grinch.Organization'),
        ),
    ]
