# Generated by Django 2.2.12 on 2020-05-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20191213_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherit_children', to='wiki.Article'),
        ),
    ]
