# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grinch', '0016_team_organization'),
        ('wiki', '0002_auto_20170118_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='grinch.Organization'),
        ),
    ]
